### ISSUE TITLE
2. api/users/createUserPost - 201 code, POST returns 404

### ISSUE THREAD

**Issue by maksx3** [Ukrainis/spring-boot-test-application#1]
api/users/createUserPost (POST) returns 404
<img width="1656" alt="Screenshot 2022-05-07 at 01 09 41" src="https://user-images.githubusercontent.com/37266806/167222481-c1dc23e6-dbb6-404d-91d1-8ed46f3fd7d7.png">

**Comment by Ukrainis** [comment]
Please check endpoint. Should be: https://spring-boot-test-aplication.herokuapp.com/api/user/createUserPost
